name: VibeStatus
options:
  bundleIdPrefix: com.vibestatus
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"

settings:
  SWIFT_VERSION: "5.9"
  MACOSX_DEPLOYMENT_TARGET: "13.0"

packages:
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle
    from: "2.5.0"

targets:
  VibeStatus:
    type: application
    platform: macOS
    sources:
      - VibeStatus
    info:
      path: VibeStatus/Info.plist
      properties:
        LSUIElement: true
        CFBundleShortVersionString: "1.3"
        CFBundleVersion: "4"
        NSHumanReadableCopyright: "Copyright © 2025. All rights reserved."
        LSApplicationCategoryType: public.app-category.utilities
        SUFeedURL: "https://raw.githubusercontent.com/Vladimirbabic/vibestatus/main/appcast.xml"
        SUPublicEDKey: ""
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.vibestatus.app
      PRODUCT_NAME: "VibeStatus"
      INFOPLIST_FILE: VibeStatus/Info.plist
      CODE_SIGN_STYLE: Automatic
      ENABLE_HARDENED_RUNTIME: YES
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - package: Sparkle
    entitlements:
      path: VibeStatus/VibeStatus.entitlements
      properties:
        com.apple.security.app-sandbox: false
    postBuildScripts:
      - name: "Sign Sparkle XPC Services"
        script: |
          # Sign Sparkle's XPC services and helpers for Hardened Runtime
          SPARKLE_FRAMEWORK="${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/Sparkle.framework"

          if [ -d "$SPARKLE_FRAMEWORK" ]; then
            # Sign XPC services
            find "$SPARKLE_FRAMEWORK" -name "*.xpc" -type d | while read xpc; do
              codesign --force --options runtime --sign "${CODE_SIGN_IDENTITY}" "$xpc"
            done

            # Sign helper apps
            find "$SPARKLE_FRAMEWORK" -name "*.app" -type d | while read app; do
              codesign --force --options runtime --sign "${CODE_SIGN_IDENTITY}" "$app"
            done

            # Sign Autoupdate
            if [ -f "$SPARKLE_FRAMEWORK/Versions/B/Autoupdate" ]; then
              codesign --force --options runtime --sign "${CODE_SIGN_IDENTITY}" "$SPARKLE_FRAMEWORK/Versions/B/Autoupdate"
            fi

            # Re-sign the framework itself
            codesign --force --options runtime --sign "${CODE_SIGN_IDENTITY}" "$SPARKLE_FRAMEWORK"
          fi
